export const TEXTURE = {
  Bg: "asset_bg.png",
  Button_down: "asset_button_down.png",
  Button_up: "asset_button_up.png",
  Gameover_popup: "asset_gameover_popup.png",
  Gem1: "asset_gem1.png",
  Gem2: "asset_gem2.png",
  Gem3: "asset_gem3.png",
  Gem4: "asset_gem4.png",
  Gem5: "asset_gem5.png",
  Gem6: "asset_gem6.png",
  Large_btn_down: "asset_large_btn_down.png",
  Large_btn_up: "asset_large_btn_up.png",
  Pause_down: "asset_pause_down.png",
  Pause_menu: "asset_pause_menu.png",
  Pause_up: "asset_pause_up.png",
  Title: "asset_title.png",
  Title_bg: "asset_title_bg.png",
  Text_container: "asset_text_container.png",
};
